<?php return array (
  'company_name' => 'My Medi Practice HR',
  'contact_person' => 'Martin palmer',
  'email' => 'support@palmeronidesign.com',
  'phone' => '0860247895',
  'city' => 'Boyle',
  'state' => 'Roscommon',
  'zipcode' => 'IRL',
  'country_id' => '115',
  'address' => 'Palmeroni Design Ltd
',
  'timezone_id' => '341',
  'default_currency' => 'Euro',
  'default_currency_symbol' => '€',
  'default_language' => 'en',
  'direction' => 'ltr',
  'allowed_upload_file' => 'pdf,doc,docx,jpg,JPG,jpeg,png',
  'allowed_upload_max_size' => '100000',
  'application_title' => 'My Medi Practice HR',
  'in_time' => '09:25',
  'out_time' => '17:45',
  'time_format' => '12hrs',
  'date_separator' => '0',
  'date_format' => 'dd MM YYYY',
  'date_separater' => '-',
  'installation_path' => '1',
  'job_application_staff' => 'yes',
  'application_format' => 'pdf,doc,docx',
  'error_display' => '1',
  'application_name' => 'My Medi Practice HR',
  'credit' => 'Copyright 2017<a href="https://palmeronidesign.com/" target="_blank"> <img style="max-height: 23px;padding: 0 5px" src="https://carrickcamping.com/wp-content/uploads/2017/03/p-logo.png" alt=""><a/>',
  'finance_ymonth' => '1',
  'leave_salary_includes' => 'on',
  'leave_encashment' => 'on',
  'Save' => 'Save',
);